VULNERABILIDADES = {
    # 1. OWASP TOP 10 (Inyección, Acceso, Autenticación)
    "SQL_INJECTION": {"nombre": "Inyección SQL (SQLi)", "severidad": "Alta", "descripcion": "Un atacante puede interferir con las consultas SQL a la base de datos a través de entradas no sanitizadas.", "solucion": "Usar sentencias preparadas (consultas parametrizadas), ORMs y validar/sanitizar estrictamente todas las entradas de usuario."},
    "XSS_STORED": {"nombre": "Cross-Site Scripting (XSS) Almacenado", "severidad": "Alta", "descripcion": "Código malicioso (script) almacenado en el servidor y servido a otros usuarios.", "solucion": "Sanitizar y codificar toda la entrada de usuario antes de almacenarla y aplicar codificación de salida."},
    "XSS_REFLECTED": {"nombre": "Cross-Site Scripting (XSS) Reflejado", "severidad": "Media", "descripcion": "El código malicioso se inyecta a través de la URL y se 'refleja' de vuelta al navegador del usuario.", "solucion": "Codificar la salida de datos no confiables de acuerdo con el contexto HTML."},
    "COMMAND_INJECTION": {"nombre": "Inyección de Comandos del Sistema Operativo", "severidad": "Alta", "descripcion": "Permite a un atacante ejecutar comandos arbitrarios del sistema operativo en el servidor.", "solucion": "Evitar las llamadas a comandos del sistema. Si es esencial, usar listas blancas."},
    "XXE_INJECTION": {"nombre": "Inyección de Entidad Externa XML (XXE)", "severidad": "Media", "descripcion": "El parser XML procesa referencias a entidades externas no confiables, exponiendo archivos internos.", "solucion": "Deshabilitar completamente la declaración de entidades externas (DTDs) en el parser XML."},
    "LDAP_INJECTION": {"nombre": "Inyección LDAP", "severidad": "Media", "descripcion": "Permite manipular las sentencias LDAP para ver o modificar el directorio de usuarios.", "solucion": "Utilizar API específicas para LDAP que escapen los caracteres de entrada."},
    "SSTI_VULNERABILITY": {"nombre": "Inyección de Plantilla del Lado del Servidor (SSTI)", "severidad": "Alta", "descripcion": "El atacante inyecta código de plantilla malicioso en datos de usuario procesados en el lado del servidor.", "solucion": "Tratar la entrada de usuario como texto plano. Si se permite la entrada de plantillas, usar sandboxing estricto."},
    "IDOR_DIRECT": {"nombre": "Referencia Directa a Objeto Insegura (IDOR)", "severidad": "Alta", "descripcion": "Un usuario puede acceder a recursos que no le pertenecen cambiando el ID en la URL.", "solucion": "Implementar un control de acceso a nivel de código que verifique la propiedad del objeto solicitado."},
    "MISSING_FUNCTION_ACCESS_CONTROL": {"nombre": "Falta Control de Acceso a Nivel de Función", "severidad": "Media", "descripcion": "Permite que un usuario normal acceda a funciones reservadas para administradores.", "solucion": "Aplicar controles de acceso estrictos en cada función/controlador y verificar el rol del usuario."},
    "CSRF_VULNERABLE": {"nombre": "Cross-Site Request Forgery (CSRF)", "severidad": "Media", "descripcion": "Un atacante puede forzar a un usuario autenticado a enviar una solicitud HTTP sin el conocimiento del usuario.", "solucion": "Implementar tokens anti-CSRF únicos por sesión o utilizar el atributo de cookie `SameSite=Strict`."},
    "HORIZONTAL_PRIV_ESCALATION": {"nombre": "Escalada de Privilegios Horizontal", "severidad": "Alta", "descripcion": "Un usuario puede acceder a recursos de *otro usuario* en el mismo nivel de privilegio.", "solucion": "Verificar que el usuario solo pueda manipular recursos asociados a su propio ID de sesión/cuenta."},
    "VERTICAL_PRIV_ESCALATION": {"nombre": "Escalada de Privilegios Vertical", "severidad": "Alta", "descripcion": "Un usuario con bajos privilegios obtiene acceso a funciones de administrador.", "solucion": "Aplicar listas de control de acceso (ACL) en el servidor."},
    "BRUTE_FORCE_NO_RATE_LIMIT": {"nombre": "Ausencia de Límite de Tasa (Rate Limiting) en Login", "severidad": "Media", "descripcion": "Permite que un atacante automatice el intento de contraseñas de forma ilimitada.", "solucion": "Implementar bloqueo de cuentas tras varios intentos fallidos y limitar el número de intentos por IP/usuario."},
    "WEAK_PASSWORD_POLICY": {"nombre": "Política de Contraseña Débil", "severidad": "Baja", "descripcion": "El sistema permite el uso de contraseñas cortas o comunes.", "solucion": "Forzar el uso de contraseñas con longitud mínima, complejidad y listas de bloqueo de contraseñas comunes."},
    "SESSION_TIMEOUT_INADEQUATE": {"nombre": "Tiempo de espera de Sesión Insuficiente", "severidad": "Media", "descripcion": "Las sesiones de usuario permanecen activas durante un tiempo excesivamente largo.", "solucion": "Implementar tiempos de inactividad cortos y forzar la reautenticación para acciones sensibles."},
    "LOGOUT_INSECURE": {"nombre": "Cierre de Sesión Inseguro", "severidad": "Baja", "descripcion": "La función de cierre de sesión no invalida el token de sesión en el lado del servidor.", "solucion": "Invalidar y eliminar el token de sesión tanto en el cliente como en el servidor."},
    "CREDENTIAL_RECOVERY_FLAW": {"nombre": "Fallo en la Recuperación de Credenciales", "severidad": "Media", "descripcion": "El proceso de 'Olvidé mi contraseña' usa tokens débiles o predecibles.", "solucion": "Usar tokens de un solo uso, fuertes y con caducidad corta, enviados por un canal seguro (ej. email)."},
    "PLAINTEXT_DATA_EXPOSED": {"nombre": "Exposición de Datos Sensibles en Texto Plano", "severidad": "Alta", "descripcion": "Datos sensibles se almacenan o transmiten sin cifrar o con cifrado débil/obsoleto.", "solucion": "Cifrar todos los datos sensibles 'en reposo' y 'en tránsito' usando algoritmos fuertes y TLS/SSL."},
    "WEAK_HASHING": {"nombre": "Uso de Hashing Débil (e.g., MD5, SHA1)", "severidad": "Media", "descripcion": "Las contraseñas se hashean con algoritmos rápidos y obsoletos.", "solucion": "Usar algoritmos modernos y lentos con 'sal' (salt) como **Bcrypt**, **Scrypt** o **Argon2**."},
    "INSECURE_DESERIALIZATION": {"nombre": "Deserialización Insegura", "severidad": "Alta", "descripcion": "La aplicación deserializa datos no confiables, lo que puede resultar en la ejecución de código remoto.", "solucion": "Evitar la deserialización de datos de fuentes no confiables. Si es necesario, usar formatos seguros."},
    
    # 2. FALLOS DE CONFIGURACIÓN Y CABECERAS HTTP
    "MISSING_HSTS": {"nombre": "Falta la cabecera Strict-Transport-Security (HSTS)", "severidad": "Media", "descripcion": "El servidor no obliga a los navegadores a usar siempre HTTPS, permitiendo ataques de degradación de protocolo.", "solucion": "Añadir la cabecera 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload'."},
    "NO_XFO": {"nombre": "Falta la cabecera X-Frame-Options", "severidad": "Baja", "descripcion": "Permite que la página sea incrustada en un <iframe>, exponiéndola a ataques de Clickjacking.", "solucion": "Añadir 'X-Frame-Options: DENY' o 'SAMEORIGIN'."},
    "NO_XCTO": {"nombre": "Falta la cabecera X-Content-Type-Options", "severidad": "Baja", "descripcion": "Permite que el navegador 'adivine' el tipo MIME (MIME Sniffing).", "solucion": "Añadir la cabecera 'X-Content-Type-Options: nosniff'."},
    "MISSING_CSP": {"nombre": "Falta la cabecera Content-Security-Policy (CSP)", "severidad": "Media", "descripcion": "Ausencia de una política de seguridad que mitigue ataques de inyección de contenido (XSS).", "solucion": "Implementar una política CSP restrictiva."},
    "NO_REFERRER_POLICY": {"nombre": "Falta la cabecera Referrer-Policy", "severidad": "Informativa", "descripcion": "Al hacer clic en enlaces externos, la URL completa de la página actual se expone.", "solucion": "Añadir la cabecera 'Referrer-Policy: strict-origin-when-cross-origin' para limitar la información compartida."},
    "MISSING_CP": {"nombre": "Falta la Cabecera Cross-Origin-Opener-Policy (COOP)", "severidad": "Baja", "descripcion": "Permite el ataque *tabnabbing* al compartir el contexto de navegación entre ventanas.", "solucion": "Usar `Cross-Origin-Opener-Policy: same-origin`."},
    "MISSING_CRP": {"nombre": "Falta la Cabecera Cross-Origin-Resource-Policy (CORP)", "severidad": "Baja", "descripcion": "Protege los recursos contra la inclusión no autorizada por sitios web de terceros.", "solucion": "Usar `Cross-Origin-Resource-Policy: same-origin` o `same-site`."},
    "CSP_INSECURE_WILDCARD": {"nombre": "CSP Inseguro (Uso de Comodines)", "severidad": "Baja", "descripcion": "La directiva `Content-Security-Policy` usa comodines (`*`) o `'unsafe-inline'`, debilitando su efectividad.", "solucion": "Eliminar los comodines y las directivas inseguras, especificando solo las fuentes de contenido permitidas."},
    "SERVER_INFO_EXPOSED": {"nombre": "Exposición de Versión del Servidor Web", "severidad": "Informativa", "descripcion": "La cabecera 'Server' expone el tipo y versión exactos del servidor.", "solucion": "Configurar el servidor para eliminar o ofuscar la cabecera 'Server'."},
    "DIRECTORY_LISTING_ENABLED": {"nombre": "Listado de Directorios Habilitado", "severidad": "Baja", "descripcion": "El servidor muestra el contenido completo de un directorio si no encuentra un archivo índice.", "solucion": "Deshabilitar la opción de listado de directorios en la configuración del servidor web."},
    "VERBOSE_ERRORS": {"nombre": "Errores Verbosos o Reveladores", "severidad": "Baja", "descripcion": "Los mensajes de error (stack traces) de la aplicación revelan información interna valiosa.", "solucion": "Deshabilitar el reporte de errores detallados en producción y mostrar solo mensajes genéricos."},
    "DEBUG_MODE_ENABLED": {"nombre": "Modo de Depuración Habilitado", "severidad": "Media", "descripcion": "El framework o aplicación está en modo de depuración, exponiendo herramientas o variables internas.", "solucion": "Asegurarse de que el modo de depuración esté siempre deshabilitado en entornos de producción."},
    "EXPOSED_BACKUP_FILES": {"nombre": "Archivos de Backup Expuestos", "severidad": "Media", "descripcion": "Archivos de configuración, código fuente o directorios de control de versiones son accesibles públicamente.", "solucion": "Configurar el servidor web para denegar el acceso a archivos de respaldo y metadatos."},
    "VULNERABLE_CMS_VERSION": {"nombre": "Versión de CMS/Framework Obsoleta", "severidad": "Media", "descripcion": "La plataforma está ejecutando una versión que contiene vulnerabilidades públicas conocidas (CVEs).", "solucion": "Mantener todo el software de la plataforma y sus componentes actualizado a la última versión estable."},
    "INFO_DISCLOSURE_PHP": {"nombre": "Divulgación de Información de PHP", "severidad": "Baja", "descripcion": "El servidor revela la versión exacta de PHP u otra tecnología backend en las cabeceras HTTP.", "solucion": "Deshabilitar esta divulgación en el archivo de configuración de PHP (`expose_php = Off`)."},
    "INSECURE_COOKIE_HTTPONLY": {"nombre": "Falta de Atributo HttpOnly en Cookie", "severidad": "Media", "descripcion": "Una cookie de sesión no tiene la bandera 'HttpOnly', permitiendo que un ataque XSS la robe.", "solucion": "Establecer la bandera 'HttpOnly' en todas las cookies que no necesitan ser accedidas por JavaScript."},
    "INSECURE_COOKIE_SECURE": {"nombre": "Falta de Atributo Secure en Cookie", "severidad": "Media", "descripcion": "Una cookie no tiene la bandera 'Secure', permitiendo que se transmita a través de una conexión HTTP no cifrada.", "solucion": "Establecer la bandera 'Secure' en todas las cookies que contengan datos sensibles."},
    "INSECURE_COOKIE_SAMESITE_NONE": {"nombre": "Atributo SameSite=None sin Secure", "severidad": "Media", "descripcion": "La cookie tiene `SameSite=None` sin el atributo `Secure`, exponiéndola a ataques CSRF en conexiones no cifradas.", "solucion": "Si se necesita `SameSite=None`, obligatoriamente debe incluir el atributo `Secure`."},
    
    # 3. FALLOS DE LÓGICA Y API (A08, A09, A10)
    "MISCONFIGURED_CORS": {"nombre": "Configuración Insegura de CORS", "severidad": "Media", "descripcion": "El encabezado `Access-Control-Allow-Origin` se establece en `*` o acepta cualquier origen sin validación.", "solucion": "Definir explícitamente y con una lista blanca los dominios permitidos para el acceso de origen cruzado."},
    "WEAK_API_KEY_USAGE": {"nombre": "Uso Débil de Claves API", "severidad": "Media", "descripcion": "Las claves API se exponen en el código del cliente o tienen permisos excesivos.", "solucion": "Implementar listas blancas de IP/dominio para las claves API. Usar claves diferentes con el principio de menor privilegio."},
    "LACK_OF_RATE_LIMITING_API": {"nombre": "Ausencia de Límite de Tasa en API", "severidad": "Media", "descripcion": "Los endpoints de la API no limitan el número de solicitudes por usuario o IP.", "solucion": "Aplicar límites de tasa consistentes en todos los endpoints de la API."},
    "FILE_UPLOAD_UNRESTRICTED": {"nombre": "Carga de Archivos Sin Restricciones", "severidad": "Alta", "descripcion": "La aplicación permite subir cualquier tipo de archivo sin validar su tipo o contenido.", "solucion": "Aplicar una lista blanca estricta de tipos de archivo permitidos, renombrar los archivos y verificar el contenido."},
    "LFI_RFI_VULNERABILITY": {"nombre": "Inclusión de Archivos Locales/Remotos (LFI/RFI)", "severidad": "Alta", "descripcion": "La aplicación usa entradas de usuario para determinar el archivo que se incluirá.", "solucion": "Evitar usar la entrada de usuario en funciones de inclusión de archivos. Usar una lista blanca de archivos permitidos."},
    "HTTP_PARAMETER_POLLUTION": {"nombre": "Contaminación de Parámetros HTTP (HPP)", "severidad": "Media", "descripcion": "Un atacante introduce múltiples valores para el mismo parámetro HTTP para bypassear la lógica de seguridad.", "solucion": "Tratar todos los parámetros de entrada como listas y consolidar o rechazar valores duplicados."},
    "INADEQUATE_LOGGING": {"nombre": "Registro y Monitoreo Insuficientes", "severidad": "Baja", "descripcion": "Faltan logs de eventos críticos, dificultando la detección y respuesta a los ataques.", "solucion": "Implementar un sistema de logging centralizado para todos los eventos de seguridad."},
    "MISSING_PERMISSIONS_POLICY": {"nombre": "Falta la Cabecera Permissions-Policy", "severidad": "Informativa", "descripcion": "Permite a los desarrolladores controlar qué APIs y funciones del navegador pueden ser utilizadas por la página.", "solucion": "Implementar `Permissions-Policy` para deshabilitar funciones no utilizadas."},
    "CONEXION_FALLIDA": {"nombre": "Fallo de Conexión o TLS", "severidad": "Alta", "descripcion": "El escáner no pudo establecer una conexión con el objetivo o la configuración TLS es insegura.", "solucion": "Verificar que el servicio esté activo y que la configuración SSL/TLS sea accesible y segura."},
}

def get_detalles_vulnerabilidad(id_vulnerabilidad):
    # detalles de una vulnerabilidad dada su ID
    return VULNERABILIDADES.get(id_vulnerabilidad, None)