USE novamind;

INSERT INTO analisis_comentarios
(comentario, emotion_label, emotion_score, stress_level, sent_pos, sent_neu, sent_neg,
categories, summary, suggestion, departamento, equipo, fecha)
VALUES
('Me siento muy agotado con la carga de trabajo actual, necesitamos más personal',
'sadness', 0.85, 'alto', 0.1, 0.2, 0.7,
'[{"label": "sobrecarga laboral", "score": 0.92}, {"label": "recursos insuficientes", "score": 0.78}]',
'Empleado agotado por exceso de trabajo, solicita más personal',
'Revisar carga de trabajo y reasignar recursos.',
'Operaciones', 'Turno A', '2025-01-15'),

('El ambiente en el equipo es muy positivo, estoy motivado con los proyectos actuales',
'joy', 0.92, 'bajo', 0.88, 0.1, 0.02,
'[{"label": "satisfacción general", "score": 0.89}, {"label": "motivación", "score": 0.85}]',
'Empleado satisfecho y motivado con el ambiente laboral',
'Reforzar reconocimientos y buenas prácticas.',
'Ventas', 'Equipo Norte', '2025-01-16'),

('Necesitamos mejores herramientas de comunicación entre departamentos',
'neutral', 0.65, 'medio', 0.3, 0.5, 0.2,
'[{"label": "comunicación", "score": 0.87}, {"label": "tecnología/herramientas", "score": 0.72}]',
'Solicitud de mejores herramientas para comunicación interdepartamental',
'Mejorar canales y tiempos de respuesta.',
'IT', 'Backend', '2025-01-17'),

('Estoy preocupado por la falta de capacitación en las nuevas tecnologías',
'fear', 0.78, 'medio', 0.2, 0.4, 0.4,
'[{"label": "formación/capacitación", "score": 0.91}, {"label": "tecnología/herramientas", "score": 0.68}]',
'Preocupación por falta de formación en nuevas tecnologías',
'Monitorear tendencia y abrir espacios de feedback.',
'IT', 'Frontend', '2025-01-18'),

('Mi supervisor no escucha nuestras sugerencias, me siento frustrado',
'anger', 0.82, 'alto', 0.1, 0.15, 0.75,
'[{"label": "liderazgo", "score": 0.94}, {"label": "comunicación", "score": 0.81}]',
'Frustración por falta de escucha por parte del supervisor',
'Agendar 1:1 para identificar factores de estrés.',
'Operaciones', 'Turno B', '2025-01-19'),

('Excelente reconocimiento del equipo directivo esta semana',
'joy', 0.88, 'bajo', 0.91, 0.08, 0.01,
'[{"label": "reconocimiento", "score": 0.95}, {"label": "motivación", "score": 0.82}]',
'Empleado agradecido por reconocimiento recibido',
'Reforzar reconocimientos y buenas prácticas.',
'Ventas', 'Equipo Sur', '2025-01-20'),

('La carga de trabajo es imposible de manejar, estoy al límite',
'sadness', 0.91, 'alto', 0.05, 0.1, 0.85,
'[{"label": "sobrecarga laboral", "score": 0.96}, {"label": "equilibrio vida-trabajo", "score": 0.84}]',
'Empleado al límite por carga de trabajo insostenible',
'Revisar carga de trabajo y reasignar recursos.',
'Operaciones', 'Turno C', '2025-01-21'),

('Me gustaría tener más flexibilidad en el horario de trabajo',
'neutral', 0.72, 'medio', 0.45, 0.4, 0.15,
'[{"label": "equilibrio vida-trabajo", "score": 0.88}, {"label": "procesos", "score": 0.61}]',
'Solicitud de mayor flexibilidad horaria',
'Monitorear tendencia y abrir espacios de feedback.',
'IT', 'DevOps', '2025-01-22'),

('Hay conflictos constantes con otro equipo que afectan el trabajo diario',
'anger', 0.79, 'alto', 0.12, 0.18, 0.7,
'[{"label": "conflictos internos", "score": 0.93}, {"label": "ambiente laboral", "score": 0.75}]',
'Conflictos interdepartamentales afectan productividad',
'Agendar 1:1 para identificar factores de estrés.',
'Ventas', 'Equipo Este', '2025-01-23'),

('El salario no es competitivo comparado con el mercado',
'sadness', 0.74, 'medio', 0.2, 0.35, 0.45,
'[{"label": "remuneración", "score": 0.91}, {"label": "reconocimiento", "score": 0.68}]',
'Insatisfacción con compensación económica',
'Monitorear tendencia y abrir espacios de feedback.',
'IT', 'Backend', '2025-01-24'),

('Me encanta el ambiente colaborativo que se ha creado en el equipo',
'joy', 0.94, 'bajo', 0.93, 0.06, 0.01,
'[{"label": "ambiente laboral", "score": 0.96}, {"label": "motivación", "score": 0.88}]',
'Empleado muy satisfecho con ambiente colaborativo',
'Reforzar reconocimientos y buenas prácticas.',
'Ventas', 'Equipo Oeste', '2025-01-25'),

('Los procesos están mal diseñados y generan mucho retrabajo',
'anger', 0.77, 'medio', 0.15, 0.3, 0.55,
'[{"label": "procesos", "score": 0.92}, {"label": "tecnología/herramientas", "score": 0.71}]',
'Frustración por procesos ineficientes que generan retrabajo',
'Monitorear tendencia y abrir espacios de feedback.',
'Operaciones', 'Turno A', '2025-01-26'),

('Necesito más apoyo del equipo de liderazgo',
'fear', 0.69, 'medio', 0.25, 0.45, 0.3,
'[{"label": "liderazgo", "score": 0.84}, {"label": "recursos insuficientes", "score": 0.67}]',
'Solicitud de mayor soporte por parte del liderazgo',
'Monitorear tendencia y abrir espacios de feedback.',
'IT', 'Frontend', '2025-01-27'),

('Estoy muy contento con las oportunidades de crecimiento que he tenido',
'joy', 0.89, 'bajo', 0.9, 0.08, 0.02,
'[{"label": "formación/capacitación", "score": 0.87}, {"label": "satisfacción general", "score": 0.91}]',
'Empleado satisfecho con oportunidades de desarrollo profesional',
'Reforzar reconocimientos y buenas prácticas.',
'Ventas', 'Equipo Norte', '2025-01-28'),

('Siento que no hay equilibrio entre vida personal y trabajo',
'sadness', 0.83, 'alto', 0.08, 0.15, 0.77,
'[{"label": "equilibrio vida-trabajo", "score": 0.94}, {"label": "sobrecarga laboral", "score": 0.82}]',
'Empleado afectado por falta de balance vida-trabajo',
'Revisar carga de trabajo y reasignar recursos.',
'Operaciones', 'Turno B', '2025-01-29'),

('Las herramientas tecnológicas que usamos están desactualizadas',
'neutral', 0.68, 'medio', 0.22, 0.5, 0.28,
'[{"label": "tecnología/herramientas", "score": 0.89}, {"label": "procesos", "score": 0.74}]',
'Comentario sobre herramientas tecnológicas obsoletas',
'Monitorear tendencia y abrir espacios de feedback.',
'IT', 'DevOps', '2025-01-30'),

('Me siento valorado por mi equipo y mis contribuciones',
'joy', 0.91, 'bajo', 0.92, 0.07, 0.01,
'[{"label": "reconocimiento", "score": 0.93}, {"label": "ambiente laboral", "score": 0.89}]',
'Empleado se siente valorado y reconocido',
'Reforzar reconocimientos y buenas prácticas.',
'Ventas', 'Equipo Sur', '2025-01-31'),

('La comunicación entre equipos es prácticamente inexistente',
'anger', 0.76, 'alto', 0.1, 0.2, 0.7,
'[{"label": "comunicación", "score": 0.95}, {"label": "conflictos internos", "score": 0.79}]',
'Crítica severa por falta de comunicación interdepartamental',
'Mejorar canales y tiempos de respuesta.',
'IT', 'Backend', '2025-02-01'),

('Estoy estresado por la cantidad de reuniones improductivas',
'sadness', 0.81, 'alto', 0.12, 0.18, 0.7,
'[{"label": "sobrecarga laboral", "score": 0.86}, {"label": "procesos", "score": 0.81}]',
'Estrés causado por exceso de reuniones sin valor',
'Revisar carga de trabajo y reasignar recursos.',
'Operaciones', 'Turno C', '2025-02-02'),

('El equipo directivo está haciendo un gran trabajo guiándonos',
'joy', 0.87, 'bajo', 0.89, 0.09, 0.02,
'[{"label": "liderazgo", "score": 0.92}, {"label": "motivación", "score": 0.86}]',
'Reconocimiento positivo hacia el equipo directivo',
'Reforzar reconocimientos y buenas prácticas.',
'Ventas', 'Equipo Este', '2025-02-03');
